export interface Translation {
  [key: string]: {
    [key: string]: string | string[][] | any;
  };
}

export const translations: Translation = {
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.tech": "Technologies",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "hero.tag": "Disponible pour de nouveaux projets",
    "hero.h1a": "Solutions",
    "hero.h1b": "Digitales",
    "hero.h1c": "Premium",
    "hero.sub": "Développeur · Designer · Créatif",
    "hero.desc": "Je transforme vos idées en expériences digitales professionnelles — sites web, applications Android, design graphique, présentations et bien plus encore.",
    "hero.cta1": "Démarrer un Projet",
    "hero.cta2": "Voir mes Services",
    "stats.projects": "Projets Réalisés",
    "stats.clients": "Clients Satisfaits",
    "stats.services": "Services Disponibles",
    "stats.years": "Années d'Expérience",
    "about.tag": "✦ À Propos de Moi",
    "about.title": "Je maîtrise les outils pour créer l'excellence",
    "about.sub": "Passionné par la technologie et le design créatif, je mets mon expertise au service de vos projets pour délivrer des résultats qui dépassent vos attentes.",
    "about.body": "Spécialisé dans le développement web, les applications Android, le design graphique et les services académiques, j'accompagne étudiants, entrepreneurs et entreprises dans la réalisation de leurs ambitions digitales avec créativité et rigueur.",
    "about.v1": "Qualité Premium",
    "about.v2": "Livraison Rapide",
    "about.v3": "Communication Fluide",
    "about.v4": "Créativité & Innovation",
    "about.v5": "Tarifs Compétitifs",
    "about.v6": "Support Continu",
    "about.cta1": "Me Contacter",
    "about.cta2": "Suivre sur Facebook",
    "services.tag": "✦ Mes Services",
    "services.title": "Tout ce dont vous avez besoin",
    "services.sub": "Des solutions digitales complètes pour propulser votre présence en ligne et vos projets.",
    "services.more": "En savoir plus",
    "portfolio.tag": "✦ Portfolio",
    "portfolio.title": "Mes Réalisations",
    "portfolio.sub": "Découvrez une sélection de projets qui illustrent la qualité et la diversité de mon travail.",
    "pf.all": "Tout",
    "pf.cat.web": "Développement Web",
    "pf.cat.design": "Design Graphique",
    "pf.cat.ppt": "PowerPoint",
    "pf.cat.brand": "Identité de Marque",
    "pf.cat.academic": "Académique",
    "pf.cat.mobile": "Application Android",
    "pf.p1.title": "Site Vitrine E-Commerce",
    "pf.p1.desc": "Site web moderne et responsive avec catalogue produits et formulaire de contact intégré.",
    "pf.p2.title": "Affiche Événementielle",
    "pf.p2.desc": "Conception d'affiches créatives pour des événements universitaires et culturels.",
    "pf.p3.title": "Soutenance de Mémoire",
    "pf.p3.desc": "Présentation professionnelle pour soutenance de master avec animations premium.",
    "pf.p4.title": "Logo & Charte Graphique",
    "pf.p4.desc": "Création d'identité visuelle complète pour une entreprise locale.",
    "pf.p5.title": "Mémoire de Master",
    "pf.p5.desc": "Rédaction et mise en page professionnelle d'un mémoire en électrotechnique.",
    "pf.p6.title": "App de Gestion",
    "pf.p6.desc": "Application Android de gestion pour PME locale avec interface intuitive.",
    "tech.tag": "✦ Technologies",
    "tech.title": "Mon Stack Technique",
    "tech.sub": "Des outils modernes et professionnels pour des résultats à la hauteur de vos ambitions.",
    "process.tag": "✦ Mon Processus",
    "process.title": "Comment je travaille",
    "process.sub": "Un processus structuré et transparent pour garantir des résultats qui vous satisfont.",
    "process.s1.title": "Prise de Contact",
    "process.s1.desc": "Vous me décrivez votre projet via WhatsApp ou Facebook. Je réponds rapidement.",
    "process.s2.title": "Analyse & Planification",
    "process.s2.desc": "J'analyse votre demande et vous propose un plan clair avec délais et tarifs.",
    "process.s3.title": "Design & Création",
    "process.s3.desc": "Je conçois votre projet avec créativité et rigueur en respectant vos objectifs.",
    "process.s4.title": "Révisions",
    "process.s4.desc": "Je vous présente le travail et intègre vos retours jusqu'à votre satisfaction.",
    "process.s5.title": "Livraison",
    "process.s5.desc": "Le projet est livré dans les délais convenus dans les formats adaptés.",
    "process.s6.title": "Support",
    "process.s6.desc": "Je reste disponible après livraison pour toute modification ou assistance.",
    "why.tag": "✦ Pourquoi Me Choisir",
    "why.title": "Ce qui me distingue",
    "why.sub": "Plus qu'un prestataire — un partenaire digital engagé pour votre réussite.",
    "why.c1.t": "Qualité Premium",
    "why.c1.d": "Chaque projet est traité avec le même niveau d'exigence que si c'était le mien.",
    "why.c2.t": "Livraison Rapide",
    "why.c2.d": "Je respecte les délais convenus. Votre temps est précieux.",
    "why.c3.t": "Communication Continue",
    "why.c3.d": "Je vous tiens informé à chaque étape. Pas de surprises.",
    "why.c4.t": "Solutions Créatives",
    "why.c4.d": "Je propose des idées nouvelles pour améliorer votre projet.",
    "why.c5.t": "Tarifs Compétitifs",
    "why.c5.d": "Des prestations professionnelles accessibles pour tous les budgets.",
    "why.c6.t": "Support Post-Livraison",
    "why.c6.d": "Je reste disponible pour vous accompagner sur le long terme.",
    "faq.tag": "✦ FAQ",
    "faq.title": "Questions Fréquentes",
    "faq.sub": "Tout ce que vous devez savoir avant de démarrer votre projet.",
    "faq.items": [
      ["Comment démarrer un projet ?", "Contactez-moi via WhatsApp ou sur Facebook. Décrivez votre projet et je vous répondrai rapidement avec un devis et un délai estimé."],
      ["Quels sont vos délais ?", "Les délais varient selon la complexité. En général : affiche 24-48h, PowerPoint 2-3 jours, site web 1-2 semaines. Tout est convenu à l'avance."],
      ["Combien de révisions ?", "Votre satisfaction est ma priorité. Je travaille avec vous jusqu'à ce que le résultat corresponde à vos attentes."],
      ["Modes de paiement ?", "Les modalités sont discutées avant le début. Généralement un acompte pour les projets importants, solde à la livraison."],
      ["Travaillez-vous hors d'Algérie ?", "Absolument. Communication via WhatsApp, Facebook ou email. Les fichiers sont livrés en format numérique."],
      ["Quelles langues ?", "Je travaille en arabe, français et anglais selon vos besoins."]
    ],
    "contact.tag": "✦ Contact",
    "contact.title": "Transformons votre idée en réalité",
    "contact.sub": "Un projet en tête ? Contactez-moi directement — je réponds rapidement.",
    "contact.wa": "WhatsApp / Téléphone",
    "form.title": "Envoyer un Message",
    "form.name": "Nom",
    "form.namePh": "Votre nom",
    "form.phone": "Téléphone",
    "form.email": "Email",
    "form.emailPh": "votre@email.com",
    "form.service": "Service souhaité",
    "form.message": "Message",
    "form.msgPh": "Décrivez votre projet...",
    "form.send": "Envoyer le Message",
    "form.sending": "Envoi en cours...",
    "form.sent": "✅ Message envoyé !",
    "footer.brand": "Hichem Bousaada — Solutions digitales créatives pour transformer vos idées en réalité.",
    "footer.nav": "Navigation",
    "footer.servicesTitle": "Services",
    "footer.copy": "© 2026 Hichem Bousaada. Tous droits réservés.",
    "modal.features": "Ce qui est inclus",
    "modal.tools": "Outils utilisés",
    "modal.cta1": "Démarrer ce Projet",
    "modal.cta2": "En savoir plus",
    "preloader.text": "Entrez dans mon monde digital..."
  },
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.tech": "Technologies",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "hero.tag": "Available for new projects",
    "hero.h1a": "Premium",
    "hero.h1b": "Digital",
    "hero.h1c": "Solutions",
    "hero.sub": "Developer · Designer · Creative",
    "hero.desc": "I transform your ideas into professional digital experiences — websites, Android apps, graphic design, presentations, and much more.",
    "hero.cta1": "Start a Project",
    "hero.cta2": "View My Services",
    "stats.projects": "Projects Done",
    "stats.clients": "Happy Clients",
    "stats.services": "Services Available",
    "stats.years": "Years of Experience",
    "about.tag": "✦ About Me",
    "about.title": "I master the tools to create excellence",
    "about.sub": "Passionate about technology and creative design, I bring my expertise to your projects to deliver results that exceed expectations.",
    "about.body": "Specialized in web development, Android apps, graphic design, and academic services, I help students, entrepreneurs, and businesses achieve their digital ambitions with creativity and precision.",
    "about.v1": "Premium Quality",
    "about.v2": "Fast Delivery",
    "about.v3": "Smooth Communication",
    "about.v4": "Creativity & Innovation",
    "about.v5": "Competitive Pricing",
    "about.v6": "Ongoing Support",
    "about.cta1": "Contact Me",
    "about.cta2": "Follow on Facebook",
    "services.tag": "✦ My Services",
    "services.title": "Everything you need",
    "services.sub": "Complete digital solutions to power your online presence and projects.",
    "services.more": "Learn more",
    "portfolio.tag": "✦ Portfolio",
    "portfolio.title": "My Work",
    "portfolio.sub": "Explore a selection of projects that showcase the quality and diversity of my work.",
    "pf.all": "All",
    "pf.cat.web": "Web Development",
    "pf.cat.design": "Graphic Design",
    "pf.cat.ppt": "PowerPoint",
    "pf.cat.brand": "Brand Identity",
    "pf.cat.academic": "Academic",
    "pf.cat.mobile": "Android App",
    "pf.p1.title": "E-Commerce Showcase",
    "pf.p1.desc": "Modern responsive website with product catalog and integrated contact form.",
    "pf.p2.title": "Event Poster",
    "pf.p2.desc": "Creative posters for university and cultural events.",
    "pf.p3.title": "Thesis Defense",
    "pf.p3.desc": "Professional presentation for master's defense with premium animations.",
    "pf.p4.title": "Logo & Brand Guide",
    "pf.p4.desc": "Complete visual identity for a local business.",
    "pf.p5.title": "Master's Thesis",
    "pf.p5.desc": "Professional writing and layout of an electrical engineering thesis.",
    "pf.p6.title": "Management App",
    "pf.p6.desc": "Android management app for a local SME with intuitive interface.",
    "tech.tag": "✦ Technologies",
    "tech.title": "My Tech Stack",
    "tech.sub": "Modern, professional tools for results that match your ambitions.",
    "process.tag": "✦ My Process",
    "process.title": "How I work",
    "process.sub": "A structured and transparent workflow to guarantee results you'll love.",
    "process.s1.title": "Initial Contact",
    "process.s1.desc": "Describe your project via WhatsApp or Facebook. I respond quickly.",
    "process.s2.title": "Analysis & Planning",
    "process.s2.desc": "I analyze your request and propose a clear plan with timelines and pricing.",
    "process.s3.title": "Design & Creation",
    "process.s3.desc": "I craft your project with creativity and rigor, respecting your vision.",
    "process.s4.title": "Revisions",
    "process.s4.desc": "I present the work and incorporate your feedback until you're satisfied.",
    "process.s5.title": "Delivery",
    "process.s5.desc": "The project is delivered on time, in the formats you need.",
    "process.s6.title": "Support",
    "process.s6.desc": "I remain available after delivery for any modifications or assistance.",
    "why.tag": "✦ Why Choose Me",
    "why.title": "What sets me apart",
    "why.sub": "More than a service provider — a committed digital partner for your success.",
    "why.c1.t": "Premium Quality",
    "why.c1.d": "Every project receives the same level of care as if it were my own.",
    "why.c2.t": "Fast Delivery",
    "why.c2.d": "I respect agreed deadlines. Your time is valuable.",
    "why.c3.t": "Continuous Communication",
    "why.c3.d": "I keep you informed at every step. No surprises.",
    "why.c4.t": "Creative Solutions",
    "why.c4.d": "I suggest new ideas to improve your project.",
    "why.c5.t": "Competitive Pricing",
    "why.c5.d": "Professional services accessible for all budgets.",
    "why.c6.t": "Post-Delivery Support",
    "why.c6.d": "I remain available to support you long-term.",
    "faq.tag": "✦ FAQ",
    "faq.title": "Frequently Asked Questions",
    "faq.sub": "Everything you need to know before starting your project.",
    "faq.items": [
      ["How do I start a project?", "Contact me via WhatsApp or on Facebook. Describe your project and I'll respond quickly with a quote and timeline."],
      ["What are your delivery times?", "Times vary by complexity. Generally: poster 24-48h, PowerPoint 2-3 days, website 1-2 weeks. Everything is agreed in advance."],
      ["How many revisions?", "Your satisfaction is my priority. I work with you until the result matches your expectations."],
      ["Payment methods?", "Terms are discussed before starting. Generally a deposit for larger projects, balance on delivery."],
      ["Do you work outside Algeria?", "Absolutely. Communication via WhatsApp, Facebook or email. Files delivered in digital format."],
      ["What languages?", "I work in Arabic, French and English depending on your needs."]
    ],
    "contact.tag": "✦ Contact",
    "contact.title": "Let's bring your idea to life",
    "contact.sub": "Have a project in mind? Contact me directly — I respond quickly.",
    "contact.wa": "WhatsApp / Phone",
    "form.title": "Send a Message",
    "form.name": "Name",
    "form.namePh": "Your name",
    "form.phone": "Phone",
    "form.email": "Email",
    "form.emailPh": "your@email.com",
    "form.service": "Desired service",
    "form.message": "Message",
    "form.msgPh": "Describe your project...",
    "form.send": "Send Message",
    "form.sending": "Sending...",
    "form.sent": "✅ Message sent!",
    "footer.brand": "Hichem Bousaada — Creative digital solutions to turn your ideas into reality.",
    "footer.nav": "Navigation",
    "footer.servicesTitle": "Services",
    "footer.copy": "© 2026 Hichem Bousaada. All rights reserved.",
    "modal.features": "What's included",
    "modal.tools": "Tools used",
    "modal.cta1": "Start This Project",
    "modal.cta2": "Learn more",
    "preloader.text": "Step into my digital world..."
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.about": "من أنا",
    "nav.services": "الخدمات",
    "nav.portfolio": "الأعمال",
    "nav.tech": "التقنيات",
    "nav.faq": "الأسئلة",
    "nav.contact": "التواصل",
    "hero.tag": "متاح لمشاريع جديدة",
    "hero.h1a": "حلول",
    "hero.h1b": "رقمية",
    "hero.h1c": "احترافية",
    "hero.sub": "مطوّر · مصمم · مبدع",
    "hero.desc": "أحوّل أفكارك إلى تجارب رقمية احترافية — مواقع ويب، تطبيقات أندرويد، تصميم جرافيك، عروض تقديمية والمزيد.",
    "hero.cta1": "ابدأ مشروعك",
    "hero.cta2": "اكتشف خدماتي",
    "stats.projects": "مشروع منجز",
    "stats.clients": "عميل راضٍ",
    "stats.services": "خدمة متاحة",
    "stats.years": "سنوات خبرة",
    "about.tag": "✦ من أنا",
    "about.title": "أتحكم في الأدوات لأصنع التميّز",
    "about.sub": "شغفي بالتقنية والتصميم الإبداعي يدفعني لتقديم نتائج تفوق توقعاتك في كل مشروع.",
    "about.body": "متخصص في تطوير المواقع، تطبيقات الأندرويد، التصميم الجرافيكي، والخدمات الأكاديمية. أرافق الطلاب وأصحاب الأعمال والشركات في تحقيق طموحاتهم الرقمية بإبداع واحترافية.",
    "about.v1": "جودة عالية",
    "about.v2": "تسليم سريع",
    "about.v3": "تواصل مستمر",
    "about.v4": "إبداع وابتكار",
    "about.v5": "أسعار تنافسية",
    "about.v6": "دعم مستمر",
    "about.cta1": "تواصل معي",
    "about.cta2": "فيسبوك",
    "services.tag": "✦ خدماتي",
    "services.title": "كل ما تحتاجه في مكان واحد",
    "services.sub": "حلول رقمية متكاملة لتعزيز حضورك الإلكتروني ومشاريعك.",
    "services.more": "اعرف أكثر",
    "portfolio.tag": "✦ الأعمال",
    "portfolio.title": "أعمالي المنجزة",
    "portfolio.sub": "استعرض مجموعة مختارة من المشاريع التي تعكس جودة وتنوع أعمالي.",
    "pf.all": "الكل",
    "pf.cat.web": "تطوير الويب",
    "pf.cat.design": "تصميم جرافيك",
    "pf.cat.ppt": "عروض PowerPoint",
    "pf.cat.brand": "الهوية البصرية",
    "pf.cat.academic": "أكاديمي",
    "pf.cat.mobile": "تطبيق أندرويد",
    "pf.p1.title": "موقع تجارة إلكترونية",
    "pf.p1.desc": "موقع ويب حديث ومتجاوب مع كتالوج منتجات ونموذج تواصل متكامل.",
    "pf.p2.title": "ملصق فعالية",
    "pf.p2.desc": "تصميم ملصقات إبداعية للفعاليات الجامعية والثقافية.",
    "pf.p3.title": "مناقشة مذكرة تخرج",
    "pf.p3.desc": "عرض تقديمي احترافي لمناقشة الماستر مع حركات متميزة.",
    "pf.p4.title": "شعار وهوية بصرية",
    "pf.p4.desc": "إنشاء هوية بصرية كاملة لشركة محلية.",
    "pf.p5.title": "مذكرة ماستر",
    "pf.p5.desc": "كتابة وتنسيق احترافي لمذكرة في الهندسة الكهربائية.",
    "pf.p6.title": "تطبيق إدارة",
    "pf.p6.desc": "تطبيق أندرويد للإدارة لمؤسسة صغيرة بواجهة بسيطة.",
    "tech.tag": "✦ التقنيات",
    "tech.title": "أدواتي التقنية",
    "tech.sub": "أدوات حديثة واحترافية لنتائج تليق بطموحاتك.",
    "process.tag": "✦ طريقة العمل",
    "process.title": "كيف أعمل",
    "process.sub": "منهجية واضحة وشفافة لضمان نتائج ترضيك.",
    "process.s1.title": "التواصل الأولي",
    "process.s1.desc": "أرسل لي رسالة عبر واتساب أو فيسبوك وسأرد بسرعة.",
    "process.s2.title": "التحليل والتخطيط",
    "process.s2.desc": "أحلل طلبك وأقترح خطة واضحة مع مواعيد وأسعار محددة.",
    "process.s3.title": "التصميم والإنشاء",
    "process.s3.desc": "أصمم مشروعك بإبداع ودقة محترمًا رؤيتك وأهدافك.",
    "process.s4.title": "المراجعات",
    "process.s4.desc": "أعرض عليك العمل وأدمج ملاحظاتك حتى تكون راضيًا تمامًا.",
    "process.s5.title": "التسليم",
    "process.s5.desc": "يُسلَّم المشروع في الموعد المتفق عليه بالصيغ المناسبة.",
    "process.s6.title": "الدعم",
    "process.s6.desc": "أبقى متاحًا بعد التسليم لأي تعديل أو مساعدة.",
    "why.tag": "✦ لماذا تختارني",
    "why.title": "ما يميزني",
    "why.sub": "أكثر من مزود خدمة — شريك رقمي ملتزم بنجاحك.",
    "why.c1.t": "جودة عالية",
    "why.c1.d": "أتعامل مع كل مشروع بنفس الاهتمام كما لو كان مشروعي الخاص.",
    "why.c2.t": "تسليم سريع",
    "why.c2.d": "أحترم المواعيد المتفق عليها. وقتك ثمين.",
    "why.c3.t": "تواصل مستمر",
    "why.c3.d": "أبقيك على اطلاع في كل خطوة. لا مفاجآت.",
    "why.c4.t": "حلول إبداعية",
    "why.c4.d": "أقترح أفكارًا جديدة لتحسين مشروعك.",
    "why.c5.t": "أسعار تنافسية",
    "why.c5.d": "خدمات احترافية بأسعار في متناول الجميع.",
    "why.c6.t": "دعم ما بعد التسليم",
    "why.c6.d": "أبقى متاحًا لمرافقتك على المدى البعيد.",
    "faq.tag": "✦ الأسئلة الشائعة",
    "faq.title": "أسئلة شائعة",
    "faq.sub": "كل ما تريد معرفته قبل البدء في مشروعك.",
    "faq.items": [
      ["كيف أبدأ مشروعًا معك؟", "تواصل معي عبر واتساب أو عبر فيسبوك. صف مشروعك وسأرد سريعًا بعرض سعر وموعد تسليم."],
      ["ما هي مواعيد التسليم؟", "تتفاوت حسب التعقيد. عمومًا: ملصق 24-48 ساعة، عرض PowerPoint 2-3 أيام، موقع ويب 1-2 أسبوع. كل شيء يُتفق عليه مسبقًا."],
      ["كم عدد التعديلات المتاحة؟", "رضاك أولويتي. أعمل معك حتى يطابق العمل توقعاتك."],
      ["ما طرق الدفع؟", "تُناقش الشروط قبل البدء. عمومًا عربون للمشاريع الكبيرة والمبلغ المتبقي عند التسليم."],
      ["هل تعمل خارج الجزائر؟", "بالتأكيد. التواصل عبر واتساب أو فيسبوك أو البريد الإلكتروني. الملفات تُسلَّم رقميًا."],
      ["ما اللغات التي تعمل بها؟", "أعمل بالعربية والفرنسية والإنجليزية حسب احتياجاتك."]
    ],
    "contact.tag": "✦ التواصل",
    "contact.title": "لنحوّل فكرتك إلى واقع",
    "contact.sub": "لديك مشروع؟ تواصل معي مباشرة — أرد بسرعة وبكل سرور.",
    "contact.wa": "واتساب / هاتف",
    "form.title": "أرسل رسالة",
    "form.name": "الاسم",
    "form.namePh": "اسمك الكامل",
    "form.phone": "الهاتف",
    "form.email": "البريد الإلكتروني",
    "form.emailPh": "بريدك@example.com",
    "form.service": "الخدمة المطلوبة",
    "form.message": "الرسالة",
    "form.msgPh": "صف مشروعك...",
    "form.send": "إرسال الرسالة",
    "form.sending": "جارٍ الإرسال...",
    "form.sent": "✅ تم الإرسال!",
    "footer.brand": "هشام بوسعادة — حلول رقمية إبداعية لتحويل أفكارك إلى واقع.",
    "footer.nav": "التنقل",
    "footer.servicesTitle": "الخدمات",
    "footer.copy": "© 2026 هشام بوسعادة. جميع الحقوق محفوظة.",
    "modal.features": "ما تتضمنه الخدمة",
    "modal.tools": "الأدوات المستخدمة",
    "modal.cta1": "ابتدئ هذا المشروع",
    "modal.cta2": "اعرف أكثر",
    "preloader.text": "أهلاً بك في عالمي الرقمي..."
  }
};

export const SERVICES_DATA = [
  {
    id: "web",
    icon: "🌐",
    color: "#00E5FF",
    rgb: "0,229,255",
    ar: {
      title: "تطوير مواقع الويب",
      desc: "تصميم وتطوير مواقع ويب حديثة، متجاوبة وسريعة تبرز علامتك التجارية وتوفر تجربة مستخدم رائعة ومتكاملة.",
      features: ["تصميم متجاوب بالكامل", "تحسين محركات البحث SEO", "لوحة تحكم سهلة الاستخدام", "سرعة وأداء فائقين"],
      tools: ["React", "Next.js", "Tailwind CSS", "WordPress", "Node.js"]
    },
    en: {
      title: "Web Development",
      desc: "Design and development of modern, responsive, and fast websites that showcase your brand and provide an outstanding user experience.",
      features: ["Fully Responsive Design", "SEO Optimization", "User-friendly Dashboard", "Ultra-fast Performance"],
      tools: ["React", "Next.js", "Tailwind CSS", "WordPress", "Node.js"]
    },
    fr: {
      title: "Développement Web",
      desc: "Conception et développement de sites web modernes, réactifs et rapides qui valorisent votre marque et offrent une expérience utilisateur optimale.",
      features: ["Design 100% Responsif", "Optimisation SEO", "Panel d'administration intuitif", "Haute Performance & Vitesse"],
      tools: ["React", "Next.js", "Tailwind CSS", "WordPress", "Node.js"]
    }
  },
  {
    id: "android",
    icon: "📱",
    color: "#8B5CF6",
    rgb: "139,92,246",
    ar: {
      title: "تطبيقات الأندرويد",
      desc: "برمجة تطبيقات أندرويد متكاملة، آمنة ومريحة للمستخدم لتلبية احتياجات مشروعك أو شركتك بفاعلية.",
      features: ["واجهات مستخدم جذابة وحصرية", "ربط قواعد البيانات السحابية", "نظام إشعارات ذكي", "دعم تقني وتحديثات مستمرة"],
      tools: ["Android Studio", "Kotlin", "Java", "Firebase", "REST APIs"]
    },
    en: {
      title: "Android Apps",
      desc: "Programming robust, secure, and user-friendly Android mobile applications that perfectly align with your business goals.",
      features: ["Bespoke & Elegant UI/UX", "Cloud Database Integration", "Push Notifications System", "Ongoing Updates & Tech Support"],
      tools: ["Android Studio", "Kotlin", "Java", "Firebase", "REST APIs"]
    },
    fr: {
      title: "Applications Android",
      desc: "Développement d'applications mobiles Android robustes, sécurisées et intuitives qui répondent parfaitement à vos objectifs professionnels.",
      features: ["Design UI/UX Sur-Mesure", "Intégration de Bases Séquentielles/Cloud", "Système de Notifications Push", "Support Technique & Mises à Jour"],
      tools: ["Android Studio", "Kotlin", "Java", "Firebase", "APIs REST"]
    }
  },
  {
    id: "design",
    icon: "🎨",
    color: "#EC4899",
    rgb: "236,72,153",
    ar: {
      title: "التصميم الجرافيكي",
      desc: "تصاميم مبتكرة وجذابة تشمل الملصقات الإعلانية، المنشورات، لافتات السوشيال ميديا وكل ما يعزز حضورك البصري.",
      features: ["أفكار إبداعية حصرية ومميزة", "جودة طباعة عالية جدًا", "تسليم ملفات المصدر الأصلية", "تعديلات مرنة وغير محدودة"],
      tools: ["Photoshop", "Illustrator", "InDesign", "Canva"]
    },
    en: {
      title: "Graphic Design",
      desc: "Creative and eye-catching designs including posters, flyers, brochures, and social media visuals to boost your presence.",
      features: ["Unique & Creative Concepts", "High-Resolution Print Files", "Original Source Files Included", "Flexible & Unlimited Revisions"],
      tools: ["Photoshop", "Illustrator", "InDesign", "Canva"]
    },
    fr: {
      title: "Design Graphique",
      desc: "Conceptions graphiques créatives et percutantes pour affiches, flyers, brochures et visuels réseaux sociaux.",
      features: ["Concepts Originaux & Créatifs", "Fichiers Haute Résolution", "Fichiers Sources Originaux fournis", "Révisions Souples & Illimitées"],
      tools: ["Photoshop", "Illustrator", "InDesign", "Canva"]
    }
  },
  {
    id: "ppt",
    icon: "🖥️",
    color: "#F97316",
    rgb: "249,115,22",
    ar: {
      title: "عروض PowerPoint",
      desc: "تصميم عروض تقديمية احترافية ومبهرة لمناقشة مذكرات التخرج، اجتماعات العمل، والمؤتمرات مع حركات وتنسيقات جذابة.",
      features: ["تصميم مخصص يتناسب مع موضوعك", "تأثيرات وحركات انتقالية ذكية", "إنفوجرافيك ورسوم بيانية احترافية", "سهولة التعديل الكامل لاحقًا"],
      tools: ["PowerPoint", "Keynote", "Google Slides", "Illustrator"]
    },
    en: {
      title: "PowerPoint Presentations",
      desc: "Outstanding professional presentation designs for thesis defenses, corporate pitches, and conferences with interactive visual assets.",
      features: ["Custom Theme & Cohesive Palette", "Sleek Animations & Transitions", "Modern Diagrams & Infographics", "Fully Customizable Source Files"],
      tools: ["PowerPoint", "Keynote", "Google Slides", "Illustrator"]
    },
    fr: {
      title: "Présentations PowerPoint",
      desc: "Conception de présentations haut de gamme pour soutenances de thèses, réunions professionnelles et conférences.",
      features: ["Thème sur mesure & Palette harmonieuse", "Animations & Transitions fluides", "Diagrammes & Infographies modernes", "Fichiers Sources Éditables"],
      tools: ["PowerPoint", "Keynote", "Google Slides", "Illustrator"]
    }
  },
  {
    id: "academic",
    icon: "🎓",
    color: "#3B82F6",
    rgb: "59,130,246",
    ar: {
      title: "الخدمات الأكاديمية",
      desc: "مساعدة الطلاب والباحثين في كتابة وتنسيق مذكرات التخرج، التقارير العلمية، والبحوث بدقة أكاديمية عالية.",
      features: ["تنسيق وتنسيق معتمد في الجامعات", "مراجعة نحوية وإملائية دقيقة", "تنظيم فائق للمراجع والاقتباسات", "سرية وأمان تام لمعلوماتك"],
      tools: ["Microsoft Word", "LaTeX", "Excel", "Google Docs"]
    },
    en: {
      title: "Academic Services",
      desc: "Supporting students and researchers with formatting, proofreading, and structuring academic papers and theses.",
      features: ["Official Academic Styling Guide", "Thorough Proofreading & Editing", "Accurate Citations & Bibliography", "100% Confidentiality & Punctuality"],
      tools: ["Microsoft Word", "LaTeX", "Excel", "Google Docs"]
    },
    fr: {
      title: "Services Académiques",
      desc: "Aide à la mise en page, correction et structuration de mémoires de fin d'études et de rapports scientifiques.",
      features: ["Mise en Page selon les Normes Universitaires", "Correction Orthographique & Style", "Citations & Références Précises", "Confidentialité Totale & Délais Respectés"],
      tools: ["Microsoft Word", "LaTeX", "Excel", "Google Docs"]
    }
  },
  {
    id: "brand",
    icon: "🆔",
    color: "#FACC15",
    rgb: "250,204,21",
    ar: {
      title: "الهوية البصرية",
      desc: "بناء هويات بصرية متكاملة للعلامات التجارية والشركات الناشئة تشمل الشعار، المطبوعات، وبطاقات الأعمال لترسيخ هويتك.",
      features: ["شعار فريد يعبر عن فكرتك", "دليل شامل للهوية البصرية", "ملفات وتصاميم جاهزة للطباعة", "تناسق رائع عبر جميع المنصات"],
      tools: ["Illustrator", "Photoshop", "InDesign", "Figma"]
    },
    en: {
      title: "Brand Identity",
      desc: "Constructing standard visual identities for startups and brands including business cards, envelopes, and brand books.",
      features: ["Custom Modern Logo Design", "Comprehensive Brand Style Guide", "Print-Ready Output Formats", "Visual Synergy Across Platforms"],
      tools: ["Illustrator", "Photoshop", "InDesign", "Figma"]
    },
    fr: {
      title: "Identité Visuelle",
      desc: "Création d'identités de marque complètes pour entreprises et startups : logos, papeterie et chartes graphiques.",
      features: ["Design de Logo Unique & Mémorable", "Charte Graphique Complète (Brand Book)", "Fichiers Prêts pour l'Impression", "Cohérence Visuelle Multicanal"],
      tools: ["Illustrator", "Photoshop", "InDesign", "Figma"]
    }
  },
  {
    id: "print",
    icon: "🖨️",
    color: "#22C55E",
    rgb: "34,197,94",
    ar: {
      title: "خدمات الطباعة",
      desc: "طباعة احترافية فائقة الجودة لجميع مستنداتك، مذكرات التخرج، البحوث، الملصقات وتجليدها بشكل أنيق.",
      features: ["أوراق ومواد ممتازة", "تجليد فاخر وحسب الطلب", "أسعار جد مناسبة للطلبة", "توصيل متوفر"],
      tools: ["High-End Printers", "Adobe PDF", "Word"]
    },
    en: {
      title: "Printing Services",
      desc: "High-quality professional printing for all your documents, theses, reports, posters, with neat binding options.",
      features: ["Premium Paper Quality", "Luxury Custom Binding", "Very Student-Friendly Prices", "Delivery Options Available"],
      tools: ["High-End Printers", "Adobe PDF", "Word"]
    },
    fr: {
      title: "Services d'Impression",
      desc: "Impression professionnelle haute qualité de tous vos documents, mémoires, rapports, affiches et reliures soignées.",
      features: ["Qualité de Papier Premium", "Reliure Soignée & Personnalisée", "Tarifs Étudiants Avantageux", "Options de Livraison"],
      tools: ["High-End Printers", "Adobe PDF", "Word"]
    }
  },
  {
    id: "cv",
    icon: "📄",
    color: "#14B8A6",
    rgb: "20,184,166",
    ar: {
      title: "السيرة الذاتية والبورتفوليو",
      desc: "تصميم سيرة ذاتية احترافية ومتوافقة مع أنظمة الفرز (ATS) تبرز مهاراتك وخبراتك لجذب مدراء التوظيف.",
      features: ["قوالب عصرية ومهنية", "صديقة لأنظمة التوظيف ATS", "ترتيب منطقي للمعلومات", "تعديل محتوى مجاني"],
      tools: ["Canva", "Illustrator", "Photoshop", "Word"]
    },
    en: {
      title: "CV & Portfolio Design",
      desc: "Design of professional and ATS-compliant CVs that highlight your skills and experiences to capture recruiters' attention.",
      features: ["Modern & Professional Layouts", "ATS-Friendly Optimization", "Logical Information Flow", "Free Content Refinement"],
      tools: ["Canva", "Illustrator", "Photoshop", "Word"]
    },
    fr: {
      title: "CV & Portfolio",
      desc: "Conception de CV professionnels et conformes aux systèmes ATS qui valorisent vos compétences et votre parcours.",
      features: ["Mises en Page Modernes", "Optimisation ATS-Friendly", "Structure Logique", "Ajustement du Contenu"],
      tools: ["Canva", "Illustrator", "Photoshop", "Word"]
    }
  },
  {
    id: "transcription",
    icon: "🎙️",
    color: "#6366F1",
    rgb: "99,102,241",
    ar: {
      title: "تفريغ التسجيلات الصوتية",
      desc: "تحويل وتفريغ المحتوى الصوتي والمرئي إلى نصوص مكتوبة ومنسقة بدقة متناهية وسرعة تسليم عالية.",
      features: ["دقة لغوية ونحوية تامة", "تدقيق إملائي صارم", "تنسيق احترافي للفقرات", "سرعة فائقة في الإنجاز"],
      tools: ["Audacity", "Word", "Express Scribe", "AI Speech-to-Text Assist"]
    },
    en: {
      title: "Audio & Video Transcription",
      desc: "Converting audio and video files into accurately transcribed and beautifully formatted text documents with quick turnaround.",
      features: ["Full Linguistic Accuracy", "Strict Spelling Checks", "Professional Paragraph Formatting", "Ultra-Fast Delivery"],
      tools: ["Audacity", "Word", "Express Scribe", "AI Speech-to-Text Assist"]
    },
    fr: {
      title: "Transcription Audio & Vidéo",
      desc: "Conversion de fichiers audio et vidéo en documents textuels transcrits avec précision et mis en forme proprement.",
      features: ["Précision Linguistique Totale", "Correction Orthographique Rigoureuse", "Mise en Page Propre", "Livraison Ultra-Rapide"],
      tools: ["Audacity", "Word", "Express Scribe", "AI Speech-to-Text Assist"]
    }
  }
];

export const PORTFOLIO_DATA = [
  { id: 1, cat: "web", tags: ["React", "Next.js", "Tailwind"] },
  { id: 2, cat: "design", tags: ["Photoshop", "Illustrator"] },
  { id: 3, cat: "ppt", tags: ["PowerPoint"] },
  { id: 4, cat: "brand", tags: ["Illustrator"] },
  { id: 5, cat: "academic", tags: ["Word", "LaTeX"] },
  { id: 6, cat: "mobile", tags: ["Android", "Firebase"] }
];

export const TECHNOLOGIES = [
  { name: "React", icon: "⚛️" },
  { name: "Next.js", icon: "▲" },
  { name: "Tailwind CSS", icon: "🎨" },
  { name: "Android", icon: "📱" },
  { name: "Firebase", icon: "🔥" },
  { name: "Photoshop", icon: "🖼️" },
  { name: "Illustrator", icon: "✏️" },
  { name: "PowerPoint", icon: "🖥️" },
  { name: "Word", icon: "📄" },
  { name: "Excel", icon: "📈" },
  { name: "AI Tools", icon: "🤖" },
  { name: "HTML & CSS", icon: "🌐" },
  { name: "JavaScript", icon: "⚡" },
  { name: "TypeScript", icon: "🔷" },
  { name: "Python", icon: "🐍" },
  { name: "MySQL", icon: "🗄️" }
];
